// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDIvboO5I4JT7ATGtZPmxaYqOqgRsSUk',
    appId: '1:443217660097:android:972cc7de1852efbde66c40',
    messagingSenderId: '443217660097',
    projectId: 'clearpay-c0485',
    storageBucket: 'clearpay-c0485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nHoC2ZHX9ybPg3Qubas1D3iE4_LPw9k',
    appId: '1:443217660097:ios:2899c14bf073732ce66c40',
    messagingSenderId: '443217660097',
    projectId: 'clearpay-c0485',
    storageBucket: 'clearpay-c0485.firebasestorage.app',
    iosBundleId: 'com.clearpay.clearpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzxX-8T37IGCAYgTXCP4cgii7MvjuEGM',
    appId: '1:443217660097:web:c860aa8dea6b4e41e66c40',
    messagingSenderId: '443217660097',
    projectId: 'clearpay-c0485',
    authDomain: 'clearpay-c0485.firebaseapp.com',
    storageBucket: 'clearpay-c0485.firebasestorage.app',
    measurementId: 'G-7QKX9YZ82B',
  );
}
